---
sudo: required

services:
  - docker

before_install:
  - 'sudo docker pull solita/ubuntu-systemd'
  - 'sudo docker build --no-cache --rm --file=ansible/tests/Dockerfile --tag=test:ansible ansible/tests'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/:ro test:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" adduser vpn_admin  --gecos "" --home /home/vpn_admin --disabled-password'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible/tests/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v -i /etc/ansible/roles/ansible/tests/inventory.yml /etc/ansible/roles/ansible/tests/test.yml --connection=local'
  - 'sudo docker exec "$(cat ${container_id})" netcat -vz localhost 22'
  - 'sudo docker exec "$(cat ${container_id})" netcat -vz -u localhost 1194'
  # - 'sudo docker exec "$(cat ${container_id})" sudo sysctl -a | grep net.ipv4.ip_forward\ =\ 1 '
  # - 'sudo docker exec "$(cat ${container_id})" sudo systemctl status openvpn@server | grep active\ \(running\) '
  - 'sudo docker rm -f "$(cat ${container_id})"'
