---
sudo: required

env:
  - distribution: ubuntu
    version: xenial

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible/tests/test.yml --syntax-check'
  # - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/nginx_role/travis/test.yml'
  # - ansible-playbook -i ansible/tests/inventory ansible/tests/test.yml --syntax-check
  # - ansible-playbook -i ansible/tests/inventory ansible/tests/test.yml --connection=local --sudo
  # - netcat -vz localhost 22
  # - netcat -vz -u localhost 1194
  # - sudo sysctl -a | grep net.ipv4.ip_forward\ =\ 1
  # - sudo systemctl status openvpn@server | grep active\ \(running\)
  - 'sudo docker rm -f "$(cat ${container_id})"'
